FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline_app ./pipeline_app

CMD ["streamlit", "run", "/app/pipeline_app/dashboard.py", "--server.address=0.0.0.0", "--server.port=8501"]