FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.pipeline.txt ./requirements.pipeline.txt
RUN pip install --no-cache-dir -r requirements.pipeline.txt

COPY pipeline_app ./pipeline_app

CMD ["python", "-m", "pipeline_app.main"]